name = "Gigabyte EAGLE GeForce RTX 4060 Ti OC ICE NVIDIA 8 GB GDDR6"


# VIDEOKAART_TEMPLATE = \
# {'brandId': 88,
#  'brandName': 'Gigabyte',
#  'mainGroup': 20,
#  'mainGroupName': 'Videokaarten',
#  'productName': 'Gigabyte EAGLE GeForce RTX 4060 Ti OC ICE NVIDIA 8 GB GDDR6',
#  'sku': '1110528',
#  'specs': [{'mainSpec': 'Design',
#             'spec': 'Aantal ventilatoren',
#             'trailer': None,
#             'value': '3 ventilator(en)'},
#            {'mainSpec': 'Design',
#             'spec': 'Kleur Product',
#             'trailer': None,
#             'value': 'Wit'},
#            {'mainSpec': 'Design',
#             'spec': 'Koeltechniek',
#             'trailer': None,
#             'value': 'GIGABYTE WINDFORCE 3X'},
#            {'mainSpec': 'Design',
#             'spec': 'Low Profile Bracket',
#             'trailer': None,
#             'value': 'Nee'},
#            {'mainSpec': 'Design',
#             'spec': 'Type koeling',
#             'trailer': None,
#             'value': 'Luchtkoeling'},
#            {'mainSpec': 'Design',
#             'spec': 'Ventilator diameter',
#             'trailer': None,
#             'value': '8 cm'},
#            {'mainSpec': 'Design',
#             'spec': 'Vormfactor',
#             'trailer': None,
#             'value': 'Full-Height/Full-Length (FH/FL)'},
#            {'mainSpec': 'Poorten & interfaces',
#             'spec': 'DisplayPort uit',
#             'trailer': None,
#             'value': '2 x'},
#            {'mainSpec': 'Poorten & interfaces',
#             'spec': 'DisplayPort versie',
#             'trailer': None,
#             'value': '1.4a'},
#            {'mainSpec': 'Poorten & interfaces',
#             'spec': 'HDMI uit',
#             'trailer': None,
#             'value': '2 x'},
#            {'mainSpec': 'Poorten & interfaces',
#             'spec': 'HDMI versie',
#             'trailer': None,
#             'value': '2.1a'},
#            {'mainSpec': 'Poorten & interfaces',
#             'spec': 'PCI Express versie',
#             'trailer': None,
#             'value': 'PCI-E 4.0'},
#            {'mainSpec': 'Processor',
#             'spec': 'CUDA',
#             'trailer': None,
#             'value': 'Ja'},
#            {'mainSpec': 'Processor',
#             'spec': 'CUDA cores',
#             'trailer': None,
#             'value': '4352'},
#            {'mainSpec': 'Processor',
#             'spec': 'DLSS versie',
#             'trailer': None,
#             'value': 'DLSS 3'},
#            {'mainSpec': 'Processor',
#             'spec': 'Frequentie van processor',
#             'trailer': None,
#             'value': '2550 MHz'},
#            {'mainSpec': 'Processor',
#             'spec': 'Grafische processor familie',
#             'trailer': None,
#             'value': 'NVIDIA'},
#            {'mainSpec': 'Processor',
#             'spec': 'Graphics Engine',
#             'trailer': None,
#             'value': 'GeForce RTX 4060 Ti'},
#            {'mainSpec': 'Processor',
#             'spec': 'LHR',
#             'trailer': None,
#             'value': 'Nee'},
#            {'mainSpec': 'Processor',
#             'spec': 'Max. display support',
#             'trailer': None,
#             'value': '4 x'},
#            {'mainSpec': 'Processor',
#             'spec': 'Maximum resolutie',
#             'trailer': None,
#             'value': '7680 x 4320 Pixels'},
#            {'mainSpec': 'Processor',
#             'spec': 'Thermal Design Power (TDP)',
#             'trailer': None,
#             'value': '160 W'},
#            {'mainSpec': 'Geheugen',
#             'spec': 'Geheugen interface',
#             'trailer': None,
#             'value': '128 bit'},
#            {'mainSpec': 'Geheugen',
#             'spec': 'Geheugen snelheid',
#             'trailer': None,
#             'value': '18 Gbps'},
#            {'mainSpec': 'Geheugen',
#             'spec': 'Kloksnelheid geheugen',
#             'trailer': None,
#             'value': '18000 MHz'},
#            {'mainSpec': 'Geheugen',
#             'spec': 'Number of pipelines',
#             'trailer': None,
#             'value': '3'},
#            {'mainSpec': 'Geheugen',
#             'spec': 'VGA Geheugen type',
#             'trailer': None,
#             'value': 'GDDR6'},
#            {'mainSpec': 'Geheugen',
#             'spec': 'Videogeheugen',
#             'trailer': None,
#             'value': '8 GB'},
#            {'mainSpec': 'Prestatie',
#             'spec': 'DirectX versie',
#             'trailer': None,
#             'value': '12.0'},
#            {'mainSpec': 'Prestatie',
#             'spec': 'Dual Link DVI',
#             'trailer': None,
#             'value': 'Nee'},
#            {'mainSpec': 'Prestatie',
#             'spec': 'Geïntegreerde TV Tuner',
#             'trailer': None,
#             'value': 'Nee'},
#            {'mainSpec': 'Prestatie',
#             'spec': 'NVIDIA G-SYNC',
#             'trailer': None,
#             'value': 'Ja'},
#            {'mainSpec': 'Prestatie',
#             'spec': 'Ondersteuning voor parallel processing',
#             'trailer': None,
#             'value': 'Niet ondersteund'},
#            {'mainSpec': 'Prestatie',
#             'spec': 'OpenGL versie',
#             'trailer': None,
#             'value': '4.6'},
#            {'mainSpec': 'Technische details',
#             'spec': 'Garantieperiode',
#             'trailer': None,
#             'value': '3 jaar'},
#            {'mainSpec': 'Energie',
#             'spec': 'Minimale voeding',
#             'trailer': None,
#             'value': '500 Watt'},
#            {'mainSpec': 'Energie',
#             'spec': 'Stroomaansluiting',
#             'trailer': None,
#             'value': '1x 8-pin'},
#            {'mainSpec': 'Inhoud van de verpakking',
#             'spec': 'Gebruiksaanwijzing',
#             'trailer': None,
#             'value': 'Ja'},
#            {'mainSpec': 'Inhoud van de verpakking',
#             'spec': 'Meegeleverde kabels',
#             'trailer': None,
#             'value': 'Stroom'},
#            {'mainSpec': 'Gewicht en omvang',
#             'spec': 'Gewicht',
#             'trailer': None,
#             'value': '640 g'},
#            {'mainSpec': 'Gewicht en omvang',
#             'spec': 'Hoogte',
#             'trailer': None,
#             'value': '41 mm'},
#            {'mainSpec': 'Gewicht en omvang',
#             'spec': 'Lengte',
#             'trailer': None,
#             'value': '272 mm'},
#            {'mainSpec': 'Gewicht en omvang',
#             'spec': 'Lengte',
#             'trailer': None,
#             'value': '272 mm'}],
#  'subGroup': 3,
#  'subGroupName': 'Nvidia Videokaarten'}


RTX_TEMPLATE = {
    "Specifications": {
        "Design": {
            "Number_of_fans": "",
            "Product_Color": "",
            "Cooling_Type": ""
        },
        "Ports_&_Interfaces": {
            "DisplayPort_out": "",
            "DisplayPort_version": "",
            "HDMI_out": "",
            "HDMI_version": "",
            "PCI_Express_version": ""
        },
        "Processor": {
            "CUDA": "",
            "CUDA_cores": "",
            "DLSS_version": "",
            "Processor_Frequency": "",
            "GPU_Max_Speed": "",
            "Graphics_Processor_Family": "",
            "Graphics_Engine": "",
            "LHR": "",
            "Max_Display_Support": ""
        },
        "Memory": {
            "Memory_Bandwidth_Max": "",
            "Memory_Interface": "",
            "Memory_Speed": "",
            "VGA_Memory_Type": "",
            "Video_Memory": ""
        },
        "Performance": {
            "DirectX_Version": "",
            "Dual_Link_DVI": "",
            "Integrated_TV_Tuner": "",
            "HDCP": "",
            "HDCP_Version": "",
            "NVIDIA_Ansel": "",
            "NVIDIA_GSYNC": "",
            "OpenGL_Version": ""
        },
        "Software": {
            "Supports_Linux": ""
        },
        "Power": {
            "Minimum_Power": "",
            "Power_Connector": ""
        },
        "Dimensions": {
            "Height": "",
            "Length": ""
        },
        "Product_Information": {
            "EAN": "",
            "Vendor_Code": "",
            "Article_Number": "",
            "Brand": "",
            "Warranty": "",
            "Available_Since": ""
        }
    }
}
